### ISSUE TITLE
TypeError: Object of type 'ProgressBarType' is not JSON serializable

### ISSUE THREAD

**Issue by plijnzaad** [jdidion/atropos#102]
When calling atropos as follows: 

 ```
atropos -a $adaptor \
       --progress none \
       --report-file report.json \
       --single-input $inputsam \
       --output-format sam \
       --log-level WARNING \
       --log-file foo/$atroposlog | ....


```
I get a half-complete json file and the error `TypeError: Object of type 'ProgressBarType' is not JSON serializable` (stderr is here: [err.txt](https://github.com/jdidion/atropos/files/4792093/err.txt) ).  *.txt and *.yaml report formats seem to work fine. Pickle (`report.pickle`) also gives an error ( `TypeError: write() argument must be str, not bytes` )

**Comment by jdidion** [comment]
Fixed in develop - will be in release alpha6
