### ISSUE TITLE
Trimmed fastq ordering is not deterministic

### ISSUE THREAD

**Issue by annamerk** [jdidion/atropos#106]
Running atropos multiple times produces fastqs with different read orders. It would be great if the ordering was deterministic. 

`atropos --threads 8 $ADAPTERS -o r1.trimmed.fastq.gz -p r2.trimmed.fastq.gz -pe1 r1.fastq.gz -pe2 r2.fastq.gz`

Otherwise is there a recommended performant way to sort the outputs?

**Comment by jdidion** [comment]
This is what the —preserve-order option is for.

**Comment by annamerk** [comment]
Oh, I missed that one. Thanks for the quick response!
