### ISSUE TITLE
N-prefixes / wildcards before an adapter sequence leads to shortening *all* reads at the 3'-end ?

### ISSUE THREAD

**Issue by plijnzaad** [jdidion/atropos#110]
I have been playing around with N{number} prefixes before an adaptor in order to get rid of the adapter and, say, (up to) 14 nucleotides before it. However, it turns out that e.g. using `-a 'N{6}GATCGTCGGACTGTAGAACTCTGAAC'` (and also the equivalent `NNNNNNGATCGTCGGACTGTAGAACTCTGAAC`) leads to shortening all reads _that do not contain any adapter whatsoever_ by the length of the N-prefix ?!   I.e. the sequence  `^ATATGCGC$` gets shortened to `^ATAT$` using adapter '`NNNNTGCA`', more or less as if the adapter is 'slid backwards' over read until it mismatches, and then the cut is made.
The incantation (atropos version 2.0.0a5.post20200601, python 3.6.1)  I used was

```
atropos -a strange=NNNNTGCA \
       --progress none \
       --report-file short-atroposreport.yaml \
       --single-input shortcase.sam \
       --output-format sam \
       --log-level INFO \
       > shortcase-trimmed.sam 2> shortcase.log

```
The input and result files are attached (all renamed to *txt because github won't allow me otherwise)

- [shortcase.sam.txt](https://github.com/jdidion/atropos/files/4926522/shortcase.sam.txt)
- [shortcase.log](https://github.com/jdidion/atropos/files/4926523/shortcase.log)
- [shortcase-trimmed.sam.txt](https://github.com/jdidion/atropos/files/4926524/shortcase-trimmed.sam.txt)
- [short-trimmed.sam.txt](https://github.com/jdidion/atropos/files/4926525/short-trimmed.sam.txt)
- [short-atroposreport.yaml.txt](https://github.com/jdidion/atropos/files/4926526/short-atroposreport.yaml.txt)

Is this the way it is supposed to work or am I doing something wrong? I think this used not to be the behaviour. 

(Incidentally, it would be _really_ useful if the N{k} syntax would be Perl-regexp-like, so that you can supply a range of lengths for the wild-card region.)

**Comment by jdidion** [comment]
Thanks for this reproducible report. That is not the intended behavior.

**Comment by jdidion** [comment]
Ah, I see the issue - you are using -a, which is for matching adapters at the end of the read. Try using -g instead.

There is also the concept of non-internal adapters (https://cutadapt.readthedocs.io/en/stable/guide.html#non-internal-5-and-3-adapters). I will open an issue to port this behavior over from Cutadapt.

**Comment by jdidion** [comment]
@plijnzaad please reopen if this doesn't solve your issue.
