### ISSUE TITLE
sequencing_adapters.fa : 404 not found

### ISSUE THREAD

**Issue by plijnzaad** [jdidion/atropos#111]
When running atropos  I always get the message that sequencing_adapters.fa cannot be found, leading to way too many warnings in my logs. Can this adapter file be made available as part of the distribution (not downloaded on the fly), or the messages be suppressed or be made less verbose? Using ` --log-level WARNING` it still generates 140 lines of logging output.  (this is version 2.0.0a5.post20200601)

**Comment by jdidion** [comment]
This was due to switching the `master` branch to `main`. This issue is fixed, but I will open a separate enhancement issue to package the file rather than fetch it from GitHub.
