### ISSUE TITLE
TypeError: can only concatenate tuple (not "list") to tuple

### ISSUE THREAD

**Issue by plijnzaad** [jdidion/atropos#112]
This is the latest version (2.0.0-alpha.6, pulled from the `develop` branch per today).
Error log is attached: [TM901.atropos.log](https://github.com/jdidion/atropos/files/5063193/TM901.atropos.log)

(`atropos --version` prints an error, see other issue #114)

**Comment by jdidion** [comment]
Fixed in develop, thanks
