### ISSUE TITLE
atropos --version exits with stack trace and error status

### ISSUE THREAD

**Issue by plijnzaad** [jdidion/atropos#114]
`atropos --version` seems to  prints the correct version string stdout, but also prints out a huge stack trace to stderr and exits with status 1.  See attachments. (I hope this is not intended, that would be unconventional)

[stdout.txt](https://github.com/jdidion/atropos/files/5063229/stdout.txt)
[stderr.txt](https://github.com/jdidion/atropos/files/5063230/stderr.txt)

**Comment by jdidion** [comment]
Fixed in develop. The program now exits with return code 0 if the --help or --version arguments are specified, and return code 1 if no arguments are specified or if an argument is missing.
