### ISSUE TITLE
multiqc support?

### ISSUE THREAD

**Issue by plijnzaad** [jdidion/atropos#118]
I see that https://github.com/jdidion/atropos-multiqc is  unfortunately archived. Is multiqc support planned for atropos 2.x ? That would be sooo useful.

**Comment by jdidion** [comment]
The PR has moved here https://github.com/ewels/MultiQC/pull/1182

It is functional, but unfortunately there's still a large amount of work todo before the PR will be approved.

**Comment by plijnzaad** [comment]
Mmm, that is a pity ... I don't have too much time (nor expertise) to help out any time soon.
