### ISSUE TITLE
Atropos generated empty gzip files are not proper gzip file

### ISSUE THREAD

**Issue by jganbat-fn** [jdidion/atropos#124]
When given 2 empty R1 and R2 fastq files, Atropos does generate 2 output files. Unfortunately if we specify it as `.gz` file it is actually not a proper gzip file. It is related to this issue fix: https://github.com/jdidion/atropos/issues/122 

Atropos version 1.1.29

Here is the bash script to replicate it,

test_R1.fastq.gz and test_R2.fastq.gz are empty files.

```
FQ1=test_R1.fastq.gz
FQ2=test_R2.fastq.gz
TFQ1=${FQ1%%.fastq.gz}.trimmed.fastq.gz
TFQ2=${FQ2%%.fastq.gz}.trimmed.fastq.gz
CORE="-T 4"

atropos trim $CORE \
 	--preserve-order \
 	--no-default-adapters \
 	-a <ANY ADAPTER> \
 	-A <ANY ADAPTER> \
 	-pe1 $FQ1 -pe2 $FQ2 -o $TFQ1 -p $TFQ2

```
When attempt to use `gzip` or `zcat` I get the following 
```
 % gunzip test_R1.trimmed.fastq.gz

gzip: empty.trim.fastq.gz: unexpected end of file
```

**Comment by jdidion** [comment]
Fixed - will be in the next release

**Comment by jganbat-fn** [comment]
> Fixed - will be in the next release

Great, thank you very much 😄

**Comment by jdidion** [comment]
Please try release 1.1.31
