### ISSUE TITLE
changes in log

### ISSUE THREAD

**Issue by cokelaer** [jdidion/atropos#13]
I've noticed that the log file format has changed. 

For instance, in the summary section
```
Total basepairs processed:                505,000 bp
     Read 1:       252,500 bp
     Read 2:       252,500 bp
```

is now:

```
Total basepairs processed:                505,000 bp
     Read 1       252,500 bp
     Read 2       252,500 bp
```

that is there is no more ":" sign

I am parsing the output in github.com/sequana/sequana project and this obviously affect my code. This is not a big deal but I was wondering is there was any rationale to change the output with respect to cutadapt output itself. I thought it was grerat  to keep the two outputs similar so that I needed only one parser ;-) 

I am also parsing the remaining of the code hoping it won't change. thanks

**Comment by jdidion** [comment]
Thanks for catching this. It is an unintended change that was introduced in re-writing the code for generating the summary file. I will add the ‘:’ back in.

Also, you might want to consider parsing the JSON output instead.

**Comment by cokelaer** [comment]
ah great, so that I do not need to update my code. 
JSON output ? I could not find that information in the --help, does that mean we just change the extension of the output

**Comment by jdidion** [comment]
To generate JSON summary, do one of the following:
* --report-file summary.json
* --report-file summary --report-formats json

You can also generate both text and json as follows: --report-file summary --report-formats txt json

I am updating the help message and the documentation about this. I also need to update the documentation to describe the JSON format exactly, but it's pretty self-explanatory if you just look at it in a text editor.

**Comment by jdidion** [comment]
It also supports yaml and pickle if you'd prefer those instead.

**Comment by cokelaer** [comment]
brilliant. thanks
