### ISSUE TITLE
cython is required at build time but not install time

### ISSUE THREAD

**Issue by tillea** [jdidion/atropos#138]
Hi,
as per some [Debian bug report](https://bugs.debian.org/1057982) cython is required to build the package but on the installed system it is not really needed.  I've fixed the Debian bug with this [patch](https://salsa.debian.org/med-team/atropos/-/blob/master/debian/patches/no_install_depends_cython.patch) you might like to take over in your next release.
Kind regards, Andreas.

**Comment by jdidion** [comment]
Thanks, fixed in the 1.1 branch.
