### ISSUE TITLE
Wrong Travis CI badge at PyPI

### ISSUE THREAD

**Issue by vmikk** [jdidion/atropos#15]
Hello!
I just noticed that the Travis CI badge for atropos at [PyPI](https://pypi.python.org/pypi/atropos) is linked to cutadapt, but not to atropos.

**Comment by jdidion** [comment]
Thanks for catching that. I'm not sure how it happened. It should be fixed
now.

On Wed, May 3, 2017 at 2:49 AM, Vladimir Mikryukov <notifications@github.com
