### ISSUE TITLE
How to specify multiple adapters?

### ISSUE THREAD

**Issue by endrebak** [jdidion/atropos#16]
Could not find this info (easily) in the docs. Is it `-b adapter1 -b adapter2` or `-b adapter1,adapter2`?

I dunno if you would ever have multiple adapters in a file, but I guess you could have multiple barcodes...

**Comment by jdidion** [comment]
See the section on multiple adapters: http://atropos.readthedocs.io/en/latest/guide.html#multiple-adapters
