### ISSUE TITLE
Add SeqPrep and Scythe to the benchmarks

### ISSUE THREAD

**Issue by jdidion** [jdidion/atropos#2]

**Comment by jdidion** [comment]
Also AdapterRemoval2 (this was requested by a reviewer)

**Comment by antonkulaga** [comment]
Do you already have sickle there? With default parameters, it behaves better in my case then atropos. For instance, it cuts Illumina Multiplexing PCR Primer by default while atropos needs additional configuration to do this.

**Comment by jdidion** [comment]
Thanks - I will work on adding it.

**Comment by jdidion** [comment]
Sickle and SeqPrep added in dev version. It seems like Sythe is abandoned so I won't add that one.

**Comment by jdidion** [comment]
Not adding Sickle or SeqPrep as neither supports multithreading. Not adding Scythe as it appears to be abandoned.
