### ISSUE TITLE
antropos detect output as fasta

### ISSUE THREAD

**Issue by antonkulaga** [jdidion/atropos#20]
Current antropos detect output is some text file that I have to parse to make use of detected adapters. It will be very useful to be able to have an option to output as fasta instead, so I will be able to use it in the other steps of the pipeline.

**Comment by jdidion** [comment]
Great idea. I'll enable fasta and json output. Probably on Monday.

**Comment by jdidion** [comment]
Use a .fasta extension on the filename, or use --output-formats fasta. You can also use the --fasta option to specify whether fasta output should be a single file, one file per input, or both. This will be in the next release.
