### ISSUE TITLE
feature idea: adapters by platform name

### ISSUE THREAD

**Issue by antonkulaga** [jdidion/atropos#28]
In the pipelines that deal with GEO it is easy (with GEOParse and other libs) to extract instument_model field from sample descripts with values like "Illumina HiSeq 2000". If users will be able to give such values to atropos instead of manually googling the adapters it would save a lot of time.

**Comment by tseemann** [comment]
I can see an adaptor file here:
https://github.com/jdidion/atropos/blob/eddbe9ce3c2b3e835ae42d4c586704da466bc240/atropos/adapters/sequencing_adapters.fa

It's not really instruments @antonkulaga but Platform + Technique, that defines the adaptors.
eg. Nextera + DNA-seq

**Comment by jdidion** [comment]
I think what you want here will be addressed by the integration of [AdapterBase](https://github.com/NCBI-Hackathons/OnlineAdapterDatabase) in 1.3. Closing as a duplicate. Please reopen if you don't think it will solve your use case.
