### ISSUE TITLE
Parallelized atropos trim produces MulticoreError

### ISSUE THREAD

**Issue by cshenanigans** [jdidion/atropos#38]
Atropos trim when parallelized with compression on worker is failing on [`finish()` command at this line](https://github.com/jdidion/atropos/blob/master/atropos/commands/trim/__init__.py#L776). 
 Related to #30.

It appears that the code initializes `cur_batch = 1` and increments this after writing each batch, thus when all batches have been written `cur_batch == total_batches + 1`, however this check expects `cur_batch == total_batches`.

What's unclear to me is why this only fails for some samples and not all, since this should always be true. I believe the fix should be simply updating [this line](https://github.com/jdidion/atropos/blob/master/atropos/commands/trim/__init__.py#L776) to `cur_batch == total_batches + 1`.

### To reproduce
```sh
atropos trim --log-level DEBUG -T 8 --preserve-order --no-default-adapters -u 6 -U 6 -o read1.trim.fastq.gz -p read2.trim.fastq.gz -pe1 read1.fastq.gz -pe2 read2.fastq.gz > trim.log
```

Causes the following error:
```
Process Result process:
Traceback (most recent call last):
  File "<PATH>/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "<PATH>/venv/lib/python3.5/site-packages/atropos/commands/trim/__init__.py", line 874, in run
    num_batches if num_batches > 0 else None)
  File "<PATH>/venv/lib/python3.5/site-packages/atropos/commands/trim/__init__.py", line 780, in finish
    total_batches))
atropos.commands.multicore.MulticoreError: OrderPreservingWriterResultHandler finishing without having seen 50482 batches
```

**Comment by cshenanigans** [comment]
@jdidion What is your planned release schedule? I see this commit was added to the larger 1.3 working branch.  Are you planning to release the bug fix in it's own release prior to 1.3, or if not when is 1.3 planned for release?

**Comment by jdidion** [comment]
I plan to release 1.1.13 tomorrow. The 1.2 release schedule is uncertain,
put probably ~1 month.

**Comment by jdidion** [comment]
Sorry, didn't get to this yesterday. I finished writing the test and released 1.1.13 just now.

**Comment by cshenanigans** [comment]
Thanks @jdidion! Are you planning to add the latest to pypi as well?

**Comment by jdidion** [comment]
Sorry about that. I released from a new laptop and didn't have my PyPI credentials set up, so the release failed and I didn't notice. It's there now.
