### ISSUE TITLE
minor discrepancy between cutadapt and atropos report 

### ISSUE THREAD

**Issue by cokelaer** [jdidion/atropos#46]
I am aware that atropos can output reports in json, which is more robust but currently I am still parsing the report in txt format and noticed this discrepancy in the single end case as compared to the cutadapt report. This is just a typo in the label. Note the correct "s" in "Reads with adapters"
```
=== Summary ===

Total reads processed:                   2,500
Reads with adapters:                         0 (0.0%)
Reads that were too short:                  18 (0.7%)
Reads written (passing filters):         2,482 (99.3%)
```

whereas in atopos 1.1.5 there is no "s" at "adapter"

```
Reads                                  records   fraction
----------------------------------- ---------- ----------
Total reads processed:                  78,316
Reads with adapter:                        330       0.4%
Reads that were too short:                 285       0.4%
```

**Comment by jdidion** [comment]
Will be fixed in 1.1.15.
