### ISSUE TITLE
atropos bioconda version 1.1.16

### ISSUE THREAD

**Issue by cokelaer** [jdidion/atropos#59]
@jdidion 
FYI, I updated atropos on bioconda  (vesrion 1.1.16). You can close this issue, which is simply informative.

**Comment by jdidion** [comment]
Thanks! Do you know if this can be automated yet? Would be nice to do as part of my release process.

**Comment by cokelaer** [comment]
AFAIK this is not possible to automate the process. You have to update the recipes but this is straightforward now that the recipes is written. you just need to change the version and md5. Then, a pull request and wait for the travis build process to succeed. This is where it may be tricky sometimes.

**Comment by jdidion** [comment]
Gotcha. I opened an issue for this after talking with Ryan Dale this past summer, but I guess there hasn’t been any movement: https://github.com/bioconda/bioconda-recipes/issues/5554 <https://github.com/bioconda/bioconda-recipes/issues/5554>
