### ISSUE TITLE
Add "auto" mode for paired-end adapter trimming

### ISSUE THREAD

**Issue by jdidion** [jdidion/atropos#60]
The new fastp trimmer has a nice feature in that it will trim overhangs after performing insert alignment without the need for adapter sequences to be specified.

This will be fairly easy to add to Atropos. Behavior in Atropos will be slightly different than fastp. In fastp, adapter sequences are only used if an insert match can't be found. Atropos will maintain it's current behavior of trying to match adapters after insert match, and falling back to adapter match if an insert match is not found.

**Comment by antonkulaga** [comment]
In other words I can just run atropos without specifing adapters and it should work?

**Comment by jdidion** [comment]
Right. For paired-end reads, it will just look for the insert overlap and trim the overhangs without trying to match adapter sequences.

**Comment by jdidion** [comment]
Duplicate of #6
