### ISSUE TITLE
Support UMI extraction

### ISSUE THREAD

**Issue by jdidion** [jdidion/atropos#61]
Some library preparations add UMIs to one or both ends of the template sequence. This new feature will support:
* [x] Removing UMIs of specified length from one or both reads in the pair.
* [x] Adding the UMIs to the read header
* [ ] Emitting the UMIs to one or a pair of FASTQ files in the same order as the reads.

**Comment by jdidion** [comment]
Thanks to @wckdouglas, this is now implemented in the develop branch!

**Comment by chapmanb** [comment]
Douglas and John;
Wow, thanks so much for working on this. We currently use either umis (https://github.com/vals/umis) or fastp (https://github.com/OpenGene/fastp#unique-molecular-identifer-umi-processing) for this but it would be awesome to be able to trim, filter and UMI process all together with atropos as an option.

Would you be able to support an option to prefix the UMI, like the `--umi_prefix` option in fastp? That would help us be able to feed output for atropos UMI labeling into downstream tools like fgbio (https://github.com/fulcrumgenomics/fgbio).

Thanks again for working on this.

**Comment by jdidion** [comment]
Hi Brad, absolutely. Could you open a separate issue for this?

**Comment by chapmanb** [comment]
John -- thanks so much for this. I've been digging into this more and realized I can do this right now by setting `--delim :UMI_`. Apologies for missing this option on an initial read. I did have one more feature related to extracting the UMI from a separate read, and raised a separate issue for this. Thanks again for atropos and considering all these inputs.

**Comment by jdidion** [comment]
Right now I'm not going to implement the writing of separate output files with UMIs. If there is a compelling use case for this, please open a separate issue.
