### ISSUE TITLE
trim nextera adapters

### ISSUE THREAD

**Issue by lmanchon** [jdidion/atropos#77]
--Hi,

i'm beginner in trimming sequence and i need somebody help in trimming Nextera adapters.
My libraries are built in paired-end (2x150bp) mode using Nextera XT kit with those adapters:

>PrefixNX/1
AGATGTGTATAAGAGACAG
>PrefixNX/2
AGATGTGTATAAGAGACAG
>Trans1
TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG
>Trans1_rc
CTGTCTCTTATACACATCTGACGCTGCCGACGA
>Trans2
GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG
>Trans2_rc
CTGTCTCTTATACACATCTCCGAGCCCACGAGAC

which parameters i need to set to clean my reads ?

thank you so much --

**Comment by jdidion** [comment]
I'd split your adapters into separate fasta files for the fw and rv adapters. Then use 

```bash
-a file:fw_adapters.fa -A file:rv_adapters.fa
```

**Comment by lmanchon** [comment]
just that and no other parameters to consider ?

**Comment by jdidion** [comment]
You're free to read the documentation regarding the other available parameters: https://atropos.readthedocs.io/en/latest/.
