### ISSUE TITLE
Atropos does not output read 2 fastq provided by `-p` argument in paired end mode

### ISSUE THREAD

**Issue by jessrosenfield** [jdidion/atropos#81]
When running this I 
```
atropos -T 8 \
 -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT \
 -o "out.1.fastq" \
 -p "out.2.fastq" \
 -pe1 "R1.fastq.gz" -pe2 "R2.fastq.gz" \
 --bisulfite truseq \
 --nextseq-trim 5 \
 --aligner insert \
 --no-default-adapters --no-cache-adapters \
 --report-file summary.txt --report-formats txt
```

When running I get output:
```
2019-06-27 18:38:57,483 INFO: This is Atropos 1.1.22 with Python 3.7.3
2019-06-27 18:38:57,486 INFO: Trimming 2 adapters with at most 10.0% errors in paired-end mode ...
```

Also, I think it's a bit misleading that it outputs `--error_rate` when running in insert mode instead of `--insert-match-adapter-error-rate`.

The output `out.1.fastq` only contains read 1 reads. However, the summary file includes read 1 and read 2 stats.

**Comment by jdidion** [comment]
Can you please generate a minimal pair of fastq files that reproduces the issue? Thanks!

**Comment by jessrosenfield** [comment]
Whoops this issue was submitted prematurely. The there was an issue in with the paths the caller was passing in causing the directories for the `-o` and `-p` to be different. Thank you so much for the prompt response, it's very appreciated.
