### ISSUE TITLE
Dockerfile is missing pip `wheel` package

### ISSUE THREAD

**Issue by nkrumm** [jdidion/atropos#89]
Hi,
Thanks for your work on this. Putting this here in case others need it:

I was not able to build the docker image using the Dockerfile, and would get the following error:

```
error: invalid command 'bdist_wheel'
```

To fix, I had to add the `wheel` package to the `RUN pip install...` command.  The the docker container builds.

**Comment by jdidion** [comment]
Thank you! I forgot to update this when I switched over to using wheels. This is now fixed in develop branch.
